version: '2.1'

services:
  web:
    container_name: web
    image: semengorbunov/fastapi-sql:latest
#    build: ./project
#    volumes:
#      - ./project:/usr/src
    networks:
      - my_net
    ports:
      - $WEB_PORT:8000
    environment:
      - DATABASE_URL=$DB_DRIVER://$DB_USER:$DB_PASSWORD@db/$DB_NAME
    entrypoint: >
      sh -c "
        echo 'Starting fastapi app...' &&
        echo 'Listening' $WEB_PORT &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    networks:
      - my_net
    healthcheck:
      test: pg_isready -U $DB_USER -d $DB_PASSWORD
      interval: 10s
      timeout: 3s
      retries: 3

networks:
  my_net:
    name: my_net
